print('#1')
import turtle as t
n=int(input('Кількість вершин багатокутника: '))
g=(n-2)*180/n
for i in range(n):
    t.forward(100)
    t.left(180-g)
t.reset()
import turtle as t
n = int(input('Кількість вершин багатокутника: '))
g = (n-2) * 180/n
if n%2==0:
    t.bgcolor('yellow')
    t.color('red')
else:
    t.bgcolor('red')
    t.color('yellow')
for i in range(n):
    t.forward(100)
    t.left(180-g)
t.reset()
t.bgcolor('white')
import turtle as t
for j in range (5):
   for i in range(3):
    t.forward(50)
    t.right(120)
    if i == 2:
        t.forward(55)
t.reset()
import turtle as t
for i in range(5):
    t.circle(50)
    t.left(72)
t.reset()
print('#2')
import turtle as t
t.left(90)
t.forward(20)
t.right(90)
t.forward(50)
t.right(90)
t.forward(20)
t.right(180)
t.forward(20)
t.left(90)
t.forward(10)
t.right(60)
t.forward(30)
t.left(120)
t.forward(30)
t.up()

t.left(120)
t.forward(60)
t.down()
t.forward(30)
t.backward(30)
t.up()

t.right(90)
t.forward(20)
t.left(160)
t.down()
t.forward(50)
t.right(140)
t.forward(50)
t.left(60)
t.up()

t.home()
t.forward(120)
t.left(90)
t.down()
t.forward(50)
t.backward(25)
t.right(90)
t.forward(30)
t.left(90)
t.backward(25)
t.forward(50)
t.right(90)
t.up()

t.forward(20)
t.right(90)
t.down()
t.forward(50)
t.left(150)
t.forward(60)
t.right(150)
t.forward(50)
t.up()
t.left(90)
t.forward(20)
t.down()

t.left(70)
t.forward(50)
t.right(140)
t.forward(50)
t.up()
t.left(70)
t.forward(30)
t.down()
t.circle(25)
t.reset()
print('#3')
import turtle as t
t.color('blue')
t.left(90)
t.forward(20)
t.right(90)
t.forward(50)
t.right(90)
t.forward(20)
t.right(180)
t.forward(20)
t.left(90)
t.forward(10)
t.right(60)
t.forward(30)
t.left(120)
t.forward(30)
t.up()
t.color('red')
t.left(120)
t.forward(60)
t.down()
t.forward(30)
t.backward(30)
t.up()

t.right(90)
t.forward(20)
t.left(160)
t.down()
t.forward(50)
t.right(140)
t.forward(50)
t.left(60)
t.up()
t.color('green')
t.home()
t.forward(120)
t.left(90)
t.down()
t.forward(50)
t.backward(25)
t.right(90)
t.forward(30)
t.left(90)
t.backward(25)
t.forward(50)
t.right(90)
t.up()
t.color('yellow')
t.forward(20)
t.right(90)
t.down()
t.forward(50)
t.left(150)
t.forward(60)
t.right(150)
t.forward(50)
t.up()
t.left(90)
t.forward(20)

t.down()
t.color('orange')
t.left(70)
t.forward(50)
t.right(140)
t.forward(50)
t.up()
t.left(70)
t.forward(30)
t.down()
t.color('aqua')
t.circle(25)
t.up()
t.color('black')
t.home()
t.right(90)
t.forward(10)
t.down()
t.left(90)
t.forward(310)
t.up()
t.home()
t.backward(10)
t.right(90)
t.down()
t.forward(20)
t.left(90)
t.forward(330)
t.left(90)
t.forward(80)
t.left(90)
t.forward(330)
t.left(90)
t.forward(60)
t.reset()
print("Вправа 4")
import turtle as t
for j in range (5):
    for i in range (3):
        t.begin_fill ()
        t.color("orange","orange")
        t.forward(50)
        t.right (120)
        if i==2:
            t.forward(55)
        t.end_fill()
t.reset()
print("Вправа 5")
import turtle as t
q=["orange","green","orange","green","orange"]
for j in range (5):
    for i in range (3):
        t.begin_fill ()
        t.color (q[j],q[j])
        t.forward(50)
        t.right (120)
        if i==2:
            t.forward(55)
        t.end_fill()